### ISSUE TITLE
Does it work from a filter list?

### ISSUE THREAD

**Issue by idontveapc** [Nikityyy/sad#1]

**Comment by Nikityyy** [comment]
Not yet, working on that!

**Comment by Nikityyy** [comment]
Added filter-lists.. Currently these are working: https://github.com/blocklistproject/Lists

Didn't try others, yet. Available on Firefox right now. Available on Edge in 7 work days.

**Comment by idontveapc** [comment]
Is it this one or not: <pre>https://blocklistproject.github.io/Lists/ads.txt</pre>

also, <pre>https://blocklistproject.github.io/Lists/adguard/ads-ags.txt</pre>

**Comment by Nikityyy** [comment]
`https://blocklistproject.github.io/Lists/ads.txt`
This one works. ↑

The other one soon.
